[package]
name = "anime-scraper"
version = "0.1.0"
authors = ["23prime <23.prime.37@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version = "3.3", features = ["rustls"] }
chrono = "0.4"
dotenv = "0.15"
env_logger = "0.9"
log = "0.4"
scraper = "0.12"
serde = "1.0"
serde_json = "1.0"
