[package]
name = "anime-scraper"
version = "0.1.0"
authors = ["23prime <23.prime.37@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3"
env_logger = "0.9"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
