FROM rust:1.63.0
WORKDIR /app

RUN rustup component add rustfmt
RUN rustup component add clippy

RUN cargo install cargo-watch cargo-edit sea-orm-cli

COPY . .

RUN cargo build
RUN cargo build --manifest-path ./migration/Cargo.toml
