FROM rust:1.67.0
WORKDIR /app

RUN apt update && apt install -y postgresql-client

RUN rustup component add rustfmt
RUN rustup component add clippy

RUN cargo install cargo-watch cargo-edit sea-orm-cli

COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs

COPY entity ./entity
COPY migration ./migration

RUN cargo build

COPY . .

RUN cargo build
RUN cargo build --manifest-path ./migration/Cargo.toml
