version: "3.7"

services:
  api:
    build:
      context: .
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env.production
    ports:
      - "8080:8080"
    command: ["./anime-api"]
    image: public.ecr.aws/m0z8x5y6/anime-api:latest
