version: "3.7"

services:
  api-local:
    build:
      context: .
      dockerfile: Dockerfile-local
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./migrations:/app/migrations
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - ./diesel.toml:/app/diesel.toml
      - ./rustfmt.toml:/app/rustfmt.toml
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: ["cargo", "watch", "-x", "run"]
    depends_on:
      - postgres

  postgres:
    image: postgres:11.12
    environment:
      POSTGRES_DB: GKBDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/postgres/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql

volumes:
  cargo-cache:
  target-cache:
