# c.f.)
# - https://github.com/actions-rs/cargo
# - https://zenn.dev/naokifujita/articles/c890954165c21f

name: Rust CI

on:
  push:
    branches:
      - main
      - master
      - develop
    paths-ignore:
      - "!**.md"
      - ".vscode/**"
  pull_request:
    branches:
      - main
      - master
      - develop
    paths-ignore:
      - "!**.md"
      - ".vscode/**"

jobs:
  build_cache:
    runs-on: ubuntu-latest

    env:
      RUSTC_FORCE_INCREMENTAL: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use cache
        uses: ./.github/actions/cargo-cache

      - name: Build
        run: cargo build

  format:
    runs-on: ubuntu-latest

    needs: build_cache

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add formatter
        run: rustup component add rustfmt

      - name: Use cache
        uses: ./.github/actions/cargo-cache

      - name: Format check
        run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest

    env:
      RUSTC_FORCE_INCREMENTAL: 1

    needs: build_cache

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add linter
        run: rustup component add clippy

      - name: Use cache
        uses: ./.github/actions/cargo-cache

      - name: Lint
        run: |
          cargo clippy --all-targets --all-features -- -D warnings \
            -A clippy::needless_return

  test:
    runs-on: ubuntu-latest

    env:
      RUSTC_FORCE_INCREMENTAL: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and cache Docker images
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "[DEBUG] List Docker images"
        run: docker images

      - name: Up DB
        run: docker compose -f docker-compose.test.yml up -d --wait

      - name: DB Migration
        run: docker compose -f docker-compose.test.yml exec api-test migration/target/debug/migration up

      - name: Test
        run: docker compose -f docker-compose.test.yml exec api-test cargo test --all -- --nocapture --test-threads=1
